var sareaArr = [{
		id: 1,
		name: "阿城-中石油服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["92", "95","98"],
			gasolineArrNo:[ ],
			dieseloilArr: ["0", "35"],
			dieseloilArrNo:["30"],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: true,
			gasStation: true,
			hotel: true,
			hotwater: true,
			repair: true,
			chargingPile: true,
			fillingStation: true,
		},
		location: [126.935137, 45.539408]
	},
	{
		id: 2,
		name: "平山服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["92", "95"],
			gasolineArrNo:[ "98"],
			dieseloilArr: ["0", "35"],
			dieseloilArrNo:["30"],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: false,
			gasStation: true,
			hotel: false,
			hotWater: false,
			repair: true,
			chargingPile: false,
			fillingStation: false,
		},
		location: [127.380809, 45.303413]
	},
	{
		id: 3,
		name: "尚志服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: [],
			gasolineArrNo:["92", "95", "98"],
			dieseloilArr: ["0", "30","35"],
			dieseloilArrNo:[],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: false,
			gasStation: true,
			hotel: false,
			hotWater: false,
			repair: true,
			chargingPile: false,
			fillingStation: false,
		},
		location: [127.950785, 45.192838]
	},
	{
		id: 4,
		name: "亚布力服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: [ "95"],
			gasolineArrNo:[ "92","98"],
			dieseloilArr: [],
			dieseloilArrNo:["0", "35","30"],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: false,
			gasStation: true,
			hotel: true,
			hotWater: false,
			repair: true,
			chargingPile: false,
			fillingStation: false,
		},
		location: [128.558647, 44.922264]
	},
	{
		id: 5,
		name: "筒子沟服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["95", "98"],
			gasolineArrNo:[ "92"],
			dieseloilArr: ["30", "35"],
			dieseloilArrNo:["0"],
		},
		service: {
			eat: true,
			superMarket: false,
			toilet: false,
			parking: true,
			gasStation: false,
			hotel: false,
			hotWater: false,
			repair: false,
			chargingPile: false,
			fillingStation: false,
		},
		location: [128.867626, 44.951014]
	},
	{
		id: 6,
		name: "雾凇岭停车区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["92", "95"],
			gasolineArrNo:[ "98"],
			dieseloilArr: ["0", "35"],
			dieseloilArrNo:["30"],
		},
		service: {
			eat: false,
			superMarket: false,
			toilet: false,
			parking: true,
			gasStation: false,
			hotel: false,
			hotWater: false,
			repair: false,
			chargingPile: false,
			fillingStation: false,
		},
		location: [129.011974, 44.88683]
	},
	{
		id: 7,
		name: "横道河子服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["92"],
			gasolineArrNo:[ "95","98"],
			dieseloilArr: [ "35"],
			dieseloilArrNo:["0","30"],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: false,
			gasStation: true,
			hotel: true,
			hotWater: false,
			repair: false,
			chargingPile: false,
			fillingStation: false,
		},
		location: [129.129422, 44.786746]
	},
	{
		id: 8,
		name: "小莫服务区",
		highWayNum: "G10",
		highWayname: "哈牡高速",
		phone: "18604688440",
		gas: {
			gasolineArr: ["92", "95", "98"],
			gasolineArrNo:[],
			dieseloilArr: ["0", "35"],
			dieseloilArrNo:["30"],
		},
		service: {
			eat: true,
			superMarket: true,
			toilet: true,
			parking: false,
			gasStation: true,
			hotel: false,
			hotWater: false,
			repair: true,
			chargingPile: false,
			fillingStation: false,
		},
		location: [129.5327, 44.538221]
	}
];